"""Analysis module - Frequency, Pattern, Stability, Criticality, Number Index, Calendar, Decade Affinity."""

from kenobase.analysis.calendar_features import (
    CalendarAnalysisResult,
    CalendarFeatures,
    analyze_calendar_correlation,
    extract_calendar_features,
    predict_next_gk1,
)
from kenobase.analysis.frequency import (
    FrequencyResult,
    PairFrequencyResult,
    calculate_frequency,
    calculate_pair_frequency,
    calculate_rolling_frequency,
    classify_numbers,
    classify_pairs,
    get_cold_numbers,
    get_hot_numbers,
)
from kenobase.analysis.number_index import (
    CorrelationResult,
    IndexResult,
    NumberIndex,
    calculate_index_correlation,
    calculate_index_table,
    export_index_table,
)
from kenobase.analysis.pattern import (
    PatternResult,
    aggregate_patterns,
    extract_patterns,
    extract_patterns_from_draws,
)
from kenobase.analysis.distribution import (
    DistributionResult,
    DistributionSummary,
    load_gq_data,
    analyze_distribution,
    detect_anomalies,
    create_summary,
)
from kenobase.analysis.near_miss import (
    NearMissResult,
    KENO_PROBABILITIES,
    calculate_expected_ratio,
    analyze_near_miss,
    analyze_all_near_miss,
    count_significant_anomalies,
)
from kenobase.analysis.reinforcement import (
    ReinforcementResult,
    load_restbetrag_data,
    calculate_regularity_score,
    analyze_trend,
    calculate_autocorrelation,
    analyze_reinforcement,
    is_suspicious,
)
from kenobase.analysis.popularity_correlation import (
    PopularityResult,
    RollingCorrelationResult,
    BIRTHDAY_NUMBERS,
    SCHOENE_ZAHLEN,
    load_gq_popularity,
    calculate_popularity_scores_heuristic,
    calculate_draw_frequency,
    aggregate_gq_to_number_popularity,
    analyze_correlation,
    analyze_rolling_correlation,
    run_hyp004_analysis,
)
from kenobase.analysis.recurrence import (
    RecurrenceResult,
    PairStabilityResult,
    GK1CorrelationResult,
    analyze_recurrence,
    analyze_pair_stability,
    calculate_gk1_correlation,
    analyze_number_streaks,
    generate_recurrence_report,
)
from kenobase.analysis.odds_correlation import (
    OddsCorrelationResult,
    NumberClassification,
    OddsAnalysisSummary,
    load_gq_winner_data,
    aggregate_winners_by_date,
    calculate_number_winner_scores,
    analyze_odds_correlation,
    classify_numbers_by_popularity,
    run_hyp010_analysis,
)
from kenobase.analysis.temporal_cycles import (
    TemporalCyclesResult,
    TemporalDimensionResult,
    NumberTemporalResult,
    analyze_temporal_cycles,
    analyze_dimension,
    analyze_holiday_proximity,
    analyze_number_temporal,
    GERMAN_HOLIDAYS,
    WEEKDAYS_DE,
    MONTHS_DE,
)
from kenobase.analysis.stake_correlation import (
    StakeCorrelationResult,
    NumberStakeClassification,
    StakeAnalysisSummary,
    StakeDrawRecord,
    load_stake_data,
    aggregate_stake_by_date,
    calculate_number_stake_scores,
    calculate_draw_frequency_from_records,
    analyze_stake_correlation,
    analyze_auszahlung_correlation,
    analyze_restbetrag_correlation,
    classify_numbers_by_stake,
    run_hyp012_analysis,
)
from kenobase.analysis.stable_numbers import (
    StableNumberResult,
    calculate_stability_score,
    analyze_stable_numbers,
    get_stable_numbers,
    export_stable_numbers,
)
from kenobase.analysis.cluster_reset import (
    ClusterEvent,
    ClusterResetResult,
    TradingSignal,
    detect_cluster_events,
    analyze_reset_probability,
    generate_trading_signals,
    generate_cluster_reset_report,
)
from kenobase.analysis.gk1_waiting import (
    WaitingTimeStats,
    ChiSquareResult,
    OutlierInfo,
    HistogramBin,
    GK1WaitingResult,
    load_gk1_summary_data,
    calculate_waiting_stats,
    calculate_histogram,
    chi_square_uniformity_test,
    detect_outliers,
    analyze_gk1_waiting,
    export_result_to_json,
    run_hyp002_waiting_analysis,
)
from kenobase.analysis.decade_affinity import (
    DecadeAffinityResult,
    NUM_DECADES,
    DECADES,
    get_decade,
    count_decade_occurrences,
    calculate_expected_pair_frequency,
    chi_square_test_single_pair,
    analyze_decade_affinity,
    get_top_affinity_pairs,
    get_anti_affinity_pairs,
    decade_pair_to_name,
    generate_affinity_report,
    run_hyp005_analysis,
)
from kenobase.analysis.sum_distribution import (
    HistogramBin as SumHistogramBin,
    SumCluster,
    ChiSquareResult as SumChiSquareResult,
    SumDistributionResult,
    calculate_sum_histogram,
    chi_square_uniformity_test as sum_chi_square_test,
    detect_sum_clusters,
    analyze_sum_distribution,
    run_sum_window_analysis,
    export_result_to_json as export_sum_result,
    plot_sum_distribution,
)
from kenobase.analysis.regional_affinity import (
    RegionalAffinityAnalysis,
    RegionalAffinityResult,
    RegionalNumberStat,
    analyze_regional_affinity,
    get_top_affinities,
)
from kenobase.analysis.longterm_balance import (
    NumberBalanceStats,
    BalanceTrigger,
    BalanceResult,
    calculate_balance_score,
    calculate_deviation_std,
    classify_balance,
    detect_balance_triggers,
    analyze_longterm_balance,
    get_underrepresented_numbers,
    get_overrepresented_numbers,
    generate_longterm_balance_report,
)
from kenobase.analysis.synthesizer import (
    KenoSynthesizer,
)
from kenobase.analysis.press_hypotheses import (
    HypothesisCandidate,
    PressHypothesesResult,
    PressHypothesesGenerator,
    generate_hypotheses_markdown,
)
from kenobase.analysis.multiweek_timing import (
    SimulationConfig,
    PositionDistribution,
    ChiSquareResult as MultiweekChiSquareResult,
    MonteCarloComparison,
    MultiweekTimingResult,
    ABO_LENGTHS,
    N_POSITION_BINS,
    simulate_random_abo_starts,
    calculate_position_distribution,
    chi_square_uniformity_test as multiweek_chi_square_test,
    compare_to_monte_carlo,
    analyze_multiweek_timing,
    to_dict as multiweek_to_dict,
    export_result_to_json as export_multiweek_result,
    run_hyp014_analysis,
)
from kenobase.analysis.jackpot_correlation import (
    GK1Event,
    NumberTypeStats,
    JackpotCorrelationResult,
    JackpotAnalysisSummary,
    BIRTHDAY_MIN,
    BIRTHDAY_MAX,
    HIGH_MIN,
    HIGH_MAX,
    DECADES as JACKPOT_DECADES,
    load_gk1_events,
    get_jackpot_dates,
    classify_number_type,
    get_decade as get_jackpot_decade,
    calculate_type_ratios,
    calculate_draw_type_features,
    chi_square_test as jackpot_chi_square_test,
    analyze_jackpot_correlation,
    calculate_number_type_stats,
    run_hyp015_analysis,
    export_result_to_json as export_jackpot_result,
)
from kenobase.analysis.house_edge_stability import (
    RollingWindowResult,
    HouseEdgeStabilityResult,
    CV_STABILITY_THRESHOLD,
    DEFAULT_WINDOWS,
    calculate_rolling_cv,
    analyze_single_window,
    analyze_house_edge_stability,
    run_house003_analysis,
    result_to_dict as house003_result_to_dict,
)

__all__ = [
    # Calendar Features (HYP-002)
    "CalendarFeatures",
    "CalendarAnalysisResult",
    "extract_calendar_features",
    "analyze_calendar_correlation",
    "predict_next_gk1",
    # Frequency
    "FrequencyResult",
    "PairFrequencyResult",
    "calculate_frequency",
    "calculate_pair_frequency",
    "calculate_rolling_frequency",
    "classify_numbers",
    "classify_pairs",
    "get_hot_numbers",
    "get_cold_numbers",
    # Number Index (HYP-005)
    "NumberIndex",
    "IndexResult",
    "CorrelationResult",
    "calculate_index_table",
    "calculate_index_correlation",
    "export_index_table",
    # Pattern
    "PatternResult",
    "extract_patterns",
    "extract_patterns_from_draws",
    "aggregate_patterns",
    # Distribution (HYP-001)
    "DistributionResult",
    "DistributionSummary",
    "load_gq_data",
    "analyze_distribution",
    "detect_anomalies",
    "create_summary",
    # Near-Miss (HYP-001)
    "NearMissResult",
    "KENO_PROBABILITIES",
    "calculate_expected_ratio",
    "analyze_near_miss",
    "analyze_all_near_miss",
    "count_significant_anomalies",
    # Reinforcement (HYP-001)
    "ReinforcementResult",
    "load_restbetrag_data",
    "calculate_regularity_score",
    "analyze_trend",
    "calculate_autocorrelation",
    "analyze_reinforcement",
    "is_suspicious",
    # Popularity Correlation (HYP-004)
    "PopularityResult",
    "RollingCorrelationResult",
    "BIRTHDAY_NUMBERS",
    "SCHOENE_ZAHLEN",
    "load_gq_popularity",
    "calculate_popularity_scores_heuristic",
    "calculate_draw_frequency",
    "aggregate_gq_to_number_popularity",
    "analyze_correlation",
    "analyze_rolling_correlation",
    "run_hyp004_analysis",
    # Recurrence (HYP-006)
    "RecurrenceResult",
    "PairStabilityResult",
    "GK1CorrelationResult",
    "analyze_recurrence",
    "analyze_pair_stability",
    "calculate_gk1_correlation",
    "analyze_number_streaks",
    "generate_recurrence_report",
    # Odds Correlation (HYP-010)
    "OddsCorrelationResult",
    "NumberClassification",
    "OddsAnalysisSummary",
    "load_gq_winner_data",
    "aggregate_winners_by_date",
    "calculate_number_winner_scores",
    "analyze_odds_correlation",
    "classify_numbers_by_popularity",
    "run_hyp010_analysis",
    # Temporal Cycles (HYP-011)
    "TemporalCyclesResult",
    "TemporalDimensionResult",
    "NumberTemporalResult",
    "analyze_temporal_cycles",
    "analyze_dimension",
    "analyze_holiday_proximity",
    "analyze_number_temporal",
    "GERMAN_HOLIDAYS",
    "WEEKDAYS_DE",
    "MONTHS_DE",
    # Stake Correlation (HYP-012)
    "StakeCorrelationResult",
    "NumberStakeClassification",
    "StakeAnalysisSummary",
    "StakeDrawRecord",
    "load_stake_data",
    "aggregate_stake_by_date",
    "calculate_number_stake_scores",
    "calculate_draw_frequency_from_records",
    "analyze_stake_correlation",
    "analyze_auszahlung_correlation",
    "analyze_restbetrag_correlation",
    "classify_numbers_by_stake",
    "run_hyp012_analysis",
    # Stable Numbers (Model Law A)
    "StableNumberResult",
    "calculate_stability_score",
    "analyze_stable_numbers",
    "get_stable_numbers",
    "export_stable_numbers",
    # Cluster Reset (HYP-003)
    "ClusterEvent",
    "ClusterResetResult",
    "TradingSignal",
    "detect_cluster_events",
    "analyze_reset_probability",
    "generate_trading_signals",
    "generate_cluster_reset_report",
    # GK1 Waiting Time (HYP-002)
    "WaitingTimeStats",
    "ChiSquareResult",
    "OutlierInfo",
    "HistogramBin",
    "GK1WaitingResult",
    "load_gk1_summary_data",
    "calculate_waiting_stats",
    "calculate_histogram",
    "chi_square_uniformity_test",
    "detect_outliers",
    "analyze_gk1_waiting",
    "export_result_to_json",
    "run_hyp002_waiting_analysis",
    # Decade Affinity (HYP-005)
    "DecadeAffinityResult",
    "NUM_DECADES",
    "DECADES",
    "get_decade",
    "count_decade_occurrences",
    "calculate_expected_pair_frequency",
    "chi_square_test_single_pair",
    "analyze_decade_affinity",
    "get_top_affinity_pairs",
    "get_anti_affinity_pairs",
    "decade_pair_to_name",
    "generate_affinity_report",
    "run_hyp005_analysis",
    # Sum Distribution (TASK-M04)
    "SumHistogramBin",
    "SumCluster",
    "SumChiSquareResult",
    "SumDistributionResult",
    "calculate_sum_histogram",
    "sum_chi_square_test",
    "detect_sum_clusters",
    "analyze_sum_distribution",
    "run_sum_window_analysis",
    "export_sum_result",
    "plot_sum_distribution",
    # Regional Affinity
    "RegionalAffinityAnalysis",
    "RegionalAffinityResult",
    "RegionalNumberStat",
    "analyze_regional_affinity",
    "get_top_affinities",
    # Longterm Balance (TASK-R05)
    "NumberBalanceStats",
    "BalanceTrigger",
    "BalanceResult",
    "calculate_balance_score",
    "calculate_deviation_std",
    "classify_balance",
    "detect_balance_triggers",
    "analyze_longterm_balance",
    "get_underrepresented_numbers",
    "get_overrepresented_numbers",
    "generate_longterm_balance_report",
    # Synthesizer (Birthday Correlation)
    "KenoSynthesizer",
    # Press Hypotheses (HYP012-001)
    "HypothesisCandidate",
    "PressHypothesesResult",
    "PressHypothesesGenerator",
    "generate_hypotheses_markdown",
    # Multiweek Timing (HYP-014)
    "SimulationConfig",
    "PositionDistribution",
    "MultiweekChiSquareResult",
    "MonteCarloComparison",
    "MultiweekTimingResult",
    "ABO_LENGTHS",
    "N_POSITION_BINS",
    "simulate_random_abo_starts",
    "calculate_position_distribution",
    "multiweek_chi_square_test",
    "compare_to_monte_carlo",
    "analyze_multiweek_timing",
    "multiweek_to_dict",
    "export_multiweek_result",
    "run_hyp014_analysis",
    # Jackpot Correlation (HYP-015)
    "GK1Event",
    "NumberTypeStats",
    "JackpotCorrelationResult",
    "JackpotAnalysisSummary",
    "BIRTHDAY_MIN",
    "BIRTHDAY_MAX",
    "HIGH_MIN",
    "HIGH_MAX",
    "JACKPOT_DECADES",
    "load_gk1_events",
    "get_jackpot_dates",
    "classify_number_type",
    "get_jackpot_decade",
    "calculate_type_ratios",
    "calculate_draw_type_features",
    "jackpot_chi_square_test",
    "analyze_jackpot_correlation",
    "calculate_number_type_stats",
    "run_hyp015_analysis",
    "export_jackpot_result",
    # House-Edge Stability (HOUSE-003)
    "RollingWindowResult",
    "HouseEdgeStabilityResult",
    "CV_STABILITY_THRESHOLD",
    "DEFAULT_WINDOWS",
    "calculate_rolling_cv",
    "analyze_single_window",
    "analyze_house_edge_stability",
    "run_house003_analysis",
    "house003_result_to_dict",
]
